production:
  adapter: sqlserver
  encoding: utf8
  mode: dblib
  dataserver: localhost:2014
  database: PPH_JAPPL
  username: sa
  password: P@$$w0rd
  timeout: 0
  login_timeout: 0

development:
  adapter: sqlserver
  encoding: utf8
  mode: dblib
  dataserver: localhost:2014
  database: PPH_JAPPL
  username: sa
  password: P@$$w0rd
  timeout: 0
  login_timeout: 0